-- 本文件由 tools/gen-h2-schema.py 从 db/migration 自动生成，请勿手工编辑。
-- 用途：集成测试（H2 MySQL 兼容模式）建表，与生产迁移脚本 classpath:db/migration 隔离。
-- 变换：索引名加表名前缀去重（H2 索引名 schema 全局唯一）；剥离 SET NAMES / ENGINE / CHARSET /
--       ADD COLUMN ... AFTER / MEDIUMTEXT 等 MySQL 专有语法。
-- schema 变更后请重新执行：python tools/gen-h2-schema.py

-- ============ V1__init.sql ============
DROP TABLE IF EXISTS `user`;
CREATE TABLE `user` ( `id` BIGINT NOT NULL COMMENT '用户主键（雪花 ID）', `phone` VARCHAR(11) NOT NULL COMMENT '手机号，登录账号', `nickname` VARCHAR(32) NOT NULL COMMENT '用户昵称', `password` VARCHAR(72) NOT NULL COMMENT 'BCrypt 密码哈希', `avatar_url` VARCHAR(255) DEFAULT NULL COMMENT '头像地址', `role` TINYINT NOT NULL DEFAULT 1 COMMENT '角色：1 读者 / 2 作者 / 3 管理员', `status` TINYINT NOT NULL DEFAULT 1 COMMENT '状态：0 禁用 / 1 正常', `is_deleted` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除：0 否 / 1 是', `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间', `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间', PRIMARY KEY (`id`), UNIQUE KEY `user_uk_phone` (`phone`), KEY `user_idx_role_status` (`role`, `status`) ) COMMENT = '用户表（读者 / 作者 / 管理员）';
DROP TABLE IF EXISTS `book`;
CREATE TABLE `book` ( `id` BIGINT NOT NULL COMMENT '作品主键', `author_id` BIGINT NOT NULL COMMENT '作者 ID → user.id', `title` VARCHAR(128) NOT NULL COMMENT '作品名称', `cover_url` VARCHAR(255) DEFAULT NULL COMMENT '封面地址', `category_id` BIGINT NOT NULL COMMENT '分类 ID', `tags` VARCHAR(128) DEFAULT NULL COMMENT '标签，逗号分隔', `intro` VARCHAR(1000) DEFAULT NULL COMMENT '作品简介', `status` TINYINT NOT NULL DEFAULT 1 COMMENT '状态：1 连载中 / 2 已完结 / 3 已下架', `word_count` INT NOT NULL DEFAULT 0 COMMENT '累计字数', `click_count` BIGINT NOT NULL DEFAULT 0 COMMENT '累计点击', `is_deleted` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除', `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间', `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间', PRIMARY KEY (`id`), KEY `book_idx_author` (`author_id`), KEY `book_idx_category` (`category_id`), KEY `book_idx_status` (`status`) ) COMMENT = '作品表';
DROP TABLE IF EXISTS `chapter`;
CREATE TABLE `chapter` ( `id` BIGINT NOT NULL COMMENT '章节主键', `book_id` BIGINT NOT NULL COMMENT '作品 ID → book.id', `chapter_no` INT NOT NULL COMMENT '章节序号', `title` VARCHAR(128) NOT NULL COMMENT '章节标题', `content` TEXT NOT NULL COMMENT '章节正文', `word_count` INT NOT NULL DEFAULT 0 COMMENT '本章字数', `status` TINYINT NOT NULL DEFAULT 0 COMMENT '状态：0 草稿 / 1 审核中 / 2 已发布 / 3 已驳回', `publish_time` DATETIME DEFAULT NULL COMMENT '发布时间（定时发布到点写入）', `is_deleted` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除', `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间', `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间', PRIMARY KEY (`id`), UNIQUE KEY `chapter_uk_book_no` (`book_id`, `chapter_no`), KEY `chapter_idx_book_status` (`book_id`, `status`) ) COMMENT = '章节表';
DROP TABLE IF EXISTS `comment`;
CREATE TABLE `comment` ( `id` BIGINT NOT NULL COMMENT '评论主键', `user_id` BIGINT NOT NULL COMMENT '评论人 ID → user.id', `book_id` BIGINT NOT NULL COMMENT '作品 ID → book.id', `chapter_id` BIGINT DEFAULT NULL COMMENT '章节 ID，书评为 NULL', `content` VARCHAR(1000) NOT NULL COMMENT '评论内容', `audit_score` DECIMAL(4,3) DEFAULT NULL COMMENT '机审风险分 0.000-1.000', `status` TINYINT NOT NULL DEFAULT 0 COMMENT '状态：0 待审 / 1 已通过 / 2 已驳回', `like_count` INT NOT NULL DEFAULT 0 COMMENT '点赞数', `is_deleted` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除', `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间', `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间', PRIMARY KEY (`id`), KEY `comment_idx_book_status` (`book_id`, `status`), KEY `comment_idx_user` (`user_id`) ) COMMENT = '评论表';
DROP TABLE IF EXISTS `reward_order`;
CREATE TABLE `reward_order` ( `id` BIGINT NOT NULL COMMENT '订单主键', `order_no` VARCHAR(32) NOT NULL COMMENT '订单号，支付回调幂等键', `user_id` BIGINT NOT NULL COMMENT '打赏人 ID → user.id', `book_id` BIGINT NOT NULL COMMENT '作品 ID → book.id', `chapter_id` BIGINT DEFAULT NULL COMMENT '章节 ID，可为空', `amount` DECIMAL(10,2) NOT NULL COMMENT '打赏金额（元）', `pay_channel` TINYINT NOT NULL DEFAULT 1 COMMENT '支付渠道：1 微信 / 2 支付宝', `status` TINYINT NOT NULL DEFAULT 0 COMMENT '状态：0 待支付 / 1 已支付 / 2 已关闭 / 3 已退款', `pay_time` DATETIME DEFAULT NULL COMMENT '支付完成时间', `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间', `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间', PRIMARY KEY (`id`), UNIQUE KEY `reward_order_uk_order_no` (`order_no`), KEY `reward_order_idx_user` (`user_id`), KEY `reward_order_idx_book` (`book_id`) ) COMMENT = '打赏订单表';
DROP TABLE IF EXISTS `bookshelf`;
CREATE TABLE `bookshelf` ( `id` BIGINT NOT NULL COMMENT '书架记录主键', `user_id` BIGINT NOT NULL COMMENT '读者 ID → user.id', `book_id` BIGINT NOT NULL COMMENT '书籍 ID → book.id', `last_chapter_id` BIGINT DEFAULT NULL COMMENT '最后阅读章节 → chapter.id', `is_deleted` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除', `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '加入书架时间', `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间', PRIMARY KEY (`id`), UNIQUE KEY `bookshelf_uk_user_book` (`user_id`, `book_id`), KEY `bookshelf_idx_user` (`user_id`) ) COMMENT = '书架表（用户与书籍多对多）';
DROP TABLE IF EXISTS `author_income`;
CREATE TABLE `author_income` ( `id` BIGINT NOT NULL COMMENT '流水主键', `author_id` BIGINT NOT NULL COMMENT '作者 ID → user.id', `book_id` BIGINT DEFAULT NULL COMMENT '作品 ID', `order_no` VARCHAR(32) DEFAULT NULL COMMENT '来源订单号（打赏分成）', `income_type` TINYINT NOT NULL COMMENT '类型：1 订阅 / 2 打赏分成 / 3 全勤奖', `amount` DECIMAL(10,2) NOT NULL COMMENT '金额（元）', `settle_month` VARCHAR(7) NOT NULL COMMENT '结算月份 YYYY-MM', `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间', PRIMARY KEY (`id`), KEY `author_income_idx_author_month` (`author_id`, `settle_month`) ) COMMENT = '作者稿酬流水表';
DROP TABLE IF EXISTS `audit_task`;
CREATE TABLE `audit_task` ( `id` BIGINT NOT NULL COMMENT '任务主键', `biz_type` TINYINT NOT NULL COMMENT '业务类型：1 章节 / 2 评论', `biz_id` BIGINT NOT NULL COMMENT '业务主键', `status` TINYINT NOT NULL DEFAULT 0 COMMENT '状态：0 待投递 / 1 已投递 / 2 已完成 / 3 死信', `retry_count` INT NOT NULL DEFAULT 0 COMMENT '重试次数', `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间', `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间', PRIMARY KEY (`id`), KEY `audit_task_idx_status` (`status`), KEY `audit_task_idx_biz` (`biz_type`, `biz_id`) ) COMMENT = '审核任务本地消息表';

-- ============ V2__seed.sql ============
INSERT INTO book (id, author_id, title, cover_url, category_id, tags, intro, status, word_count, click_count) VALUES (1001, 1, '万古剑尊', 'https://cover.moyue.com/1001.jpg', 1, '玄幻,热血', '少年持剑，踏碎凌霄，谱写一段热血传奇。', 1, 3280000, 102400), (1002, 1, '都市潜龙', 'https://cover.moyue.com/1002.jpg', 2, '都市', '隐世强者重归都市，笑看风云变幻。', 1, 1560000, 88110), (1003, 1, '医品风流', 'https://cover.moyue.com/1003.jpg', 2, '都市', '一手银针悬壶济世，一手妙手逆转乾坤。', 1, 980000, 55300), (1004, 1, '完美世界', 'https://cover.moyue.com/1004.jpg', 1, '玄幻', '一粒尘可填海，一根草斩尽日月星辰。', 2, 5200000, 230000), (1005, 1, '诡秘之主', 'https://cover.moyue.com/1005.jpg', 3, '悬疑', '蒸汽与机械的纪元，神秘与诡秘交织。', 1, 2400000, 176500);
INSERT INTO chapter (id, book_id, chapter_no, title, content, word_count, status, publish_time) VALUES (2001, 1001, 1, '第一章 觉醒', '剑气纵横三万里，一剑光寒十九洲。', 1200, 2, NOW()), (2002, 1001, 2, '第二章 试炼', '山门前的石阶泛着寒光，少年拾级而上。', 1500, 2, NOW()), (2003, 1004, 1, '第一章 误入', '石村的孩子名叫石昊，自石毅出生后便与众不同。', 1800, 2, NOW());
INSERT INTO comment (id, user_id, book_id, content, status, like_count) VALUES (3001, 1, 1001, '开篇即燃，追定了！', 1, 128), (3002, 1, 1004, '辰东的脑洞永远在线。', 1, 256);

-- ============ V3__message.sql ============
CREATE TABLE IF NOT EXISTS `notice` ( `id` BIGINT NOT NULL COMMENT '通知主键', `user_id` BIGINT NOT NULL COMMENT '接收用户 → user.id', `title` VARCHAR(128) NOT NULL COMMENT '标题', `content` VARCHAR(500) DEFAULT NULL COMMENT '内容', `type` TINYINT NOT NULL DEFAULT 1 COMMENT '类型：1 系统 / 2 互动 / 3 审核', `is_read` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否已读', `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间', PRIMARY KEY (`id`), KEY `notice_idx_user` (`user_id`) ) COMMENT = '站内信/通知表';

-- ============ V4__feature_im_points_blog.sql ============
DROP TABLE IF EXISTS `chat_conversation`;
CREATE TABLE `chat_conversation` ( `id` BIGINT NOT NULL COMMENT '会话主键', `type` TINYINT NOT NULL DEFAULT 1 COMMENT '类型：1 单聊 / 2 群聊', `title` VARCHAR(64) DEFAULT NULL COMMENT '群聊名称；单聊为空', `owner_id` BIGINT DEFAULT NULL COMMENT '群主 / 创建人 → user.id', `last_message` VARCHAR(512) DEFAULT NULL COMMENT '最近一条消息预览', `last_message_time` DATETIME DEFAULT NULL COMMENT '最近消息时间', `is_deleted` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除', `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间', `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间', PRIMARY KEY (`id`), KEY `chat_conversation_idx_owner` (`owner_id`), KEY `chat_conversation_idx_type` (`type`) ) COMMENT = '聊天会话表（单聊 / 群聊）';
DROP TABLE IF EXISTS `chat_conversation_member`;
CREATE TABLE `chat_conversation_member` ( `id` BIGINT NOT NULL COMMENT '主键', `conversation_id` BIGINT NOT NULL COMMENT '会话 ID → chat_conversation.id', `user_id` BIGINT NOT NULL COMMENT '成员 ID → user.id', `role` TINYINT NOT NULL DEFAULT 2 COMMENT '角色：1 群主 / 2 成员', `last_read_message_id` BIGINT DEFAULT NULL COMMENT '最后已读消息 ID', `is_deleted` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除', `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '加入时间', `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间', PRIMARY KEY (`id`), UNIQUE KEY `chat_conversation_member_uk_conv_user` (`conversation_id`, `user_id`), KEY `chat_conversation_member_idx_user` (`user_id`) ) COMMENT = '会话成员关系表';
DROP TABLE IF EXISTS `chat_message`;
CREATE TABLE `chat_message` ( `id` BIGINT NOT NULL COMMENT '消息主键', `conversation_id` BIGINT NOT NULL COMMENT '会话 ID → chat_conversation.id', `sender_id` BIGINT NOT NULL COMMENT '发送人 → user.id', `content` VARCHAR(2000) NOT NULL COMMENT '消息内容', `type` TINYINT NOT NULL DEFAULT 1 COMMENT '类型：1 文本 / 2 图片 / 3 系统', `status` TINYINT NOT NULL DEFAULT 0 COMMENT '状态：0 已发送 / 1 已读', `is_deleted` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除', `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '发送时间', `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间', PRIMARY KEY (`id`), KEY `chat_message_idx_conv_time` (`conversation_id`, `create_time`) ) COMMENT = '聊天消息表';
DROP TABLE IF EXISTS `points_account`;
CREATE TABLE `points_account` ( `user_id` BIGINT NOT NULL COMMENT '用户 ID（主键）→ user.id', `balance` INT NOT NULL DEFAULT 0 COMMENT '当前积分余额', `total_earned` INT NOT NULL DEFAULT 0 COMMENT '累计获得', `total_spent` INT NOT NULL DEFAULT 0 COMMENT '累计消费', `is_deleted` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除', `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间', `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间', PRIMARY KEY (`user_id`) ) COMMENT = '用户积分账户表';
DROP TABLE IF EXISTS `points_product`;
CREATE TABLE `points_product` ( `id` BIGINT NOT NULL COMMENT '商品主键', `name` VARCHAR(64) NOT NULL COMMENT '商品名称', `description` VARCHAR(255) DEFAULT NULL COMMENT '商品描述', `image_url` VARCHAR(255) DEFAULT NULL COMMENT '商品图片', `cost_points` INT NOT NULL DEFAULT 0 COMMENT '兑换所需积分', `stock` INT NOT NULL DEFAULT 0 COMMENT '库存', `status` TINYINT NOT NULL DEFAULT 1 COMMENT '状态：1 上架 / 2 下架', `is_deleted` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除', `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间', `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间', PRIMARY KEY (`id`), KEY `points_product_idx_status` (`status`) ) COMMENT = '积分商城商品表';
DROP TABLE IF EXISTS `points_order`;
CREATE TABLE `points_order` ( `id` BIGINT NOT NULL COMMENT '订单主键', `user_id` BIGINT NOT NULL COMMENT '兑换人 → user.id', `product_id` BIGINT NOT NULL COMMENT '商品 ID → points_product.id', `product_name` VARCHAR(64) DEFAULT NULL COMMENT '商品名称快照', `cost_points` INT NOT NULL DEFAULT 0 COMMENT '兑换消耗积分', `status` TINYINT NOT NULL DEFAULT 0 COMMENT '状态：0 待兑换 / 1 已兑换 / 2 已取消', `is_deleted` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除', `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间', `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间', PRIMARY KEY (`id`), KEY `points_order_idx_user` (`user_id`), KEY `points_order_idx_product` (`product_id`) ) COMMENT = '积分兑换订单表';
DROP TABLE IF EXISTS `blog_post`;
CREATE TABLE `blog_post` ( `id` BIGINT NOT NULL COMMENT '文章主键', `author_id` BIGINT NOT NULL COMMENT '作者 → user.id', `title` VARCHAR(128) NOT NULL COMMENT '标题', `cover_url` VARCHAR(255) DEFAULT NULL COMMENT '封面', `summary` VARCHAR(255) DEFAULT NULL COMMENT '摘要', `content` TEXT NOT NULL COMMENT '正文', `status` TINYINT NOT NULL DEFAULT 1 COMMENT '状态：0 草稿 / 1 已发布 / 2 已下架', `like_count` INT NOT NULL DEFAULT 0 COMMENT '点赞数', `comment_count` INT NOT NULL DEFAULT 0 COMMENT '评论数', `view_count` INT NOT NULL DEFAULT 0 COMMENT '浏览数', `is_deleted` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除', `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间', `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间', PRIMARY KEY (`id`), KEY `blog_post_idx_author` (`author_id`), KEY `blog_post_idx_status` (`status`) ) COMMENT = '博客文章表';
DROP TABLE IF EXISTS `blog_comment`;
CREATE TABLE `blog_comment` ( `id` BIGINT NOT NULL COMMENT '评论主键', `post_id` BIGINT NOT NULL COMMENT '文章 ID → blog_post.id', `user_id` BIGINT NOT NULL COMMENT '评论人 → user.id', `content` VARCHAR(1000) NOT NULL COMMENT '评论内容', `like_count` INT NOT NULL DEFAULT 0 COMMENT '点赞数', `is_deleted` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除', `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间', `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间', PRIMARY KEY (`id`), KEY `blog_comment_idx_post` (`post_id`), KEY `blog_comment_idx_user` (`user_id`) ) COMMENT = '博客评论表';
DROP TABLE IF EXISTS `blog_like`;
CREATE TABLE `blog_like` ( `id` BIGINT NOT NULL COMMENT '主键', `post_id` BIGINT NOT NULL COMMENT '文章 ID → blog_post.id', `user_id` BIGINT NOT NULL COMMENT '点赞人 → user.id', `is_deleted` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除', `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间', `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间', PRIMARY KEY (`id`), UNIQUE KEY `blog_like_uk_post_user` (`post_id`, `user_id`), KEY `blog_like_idx_post` (`post_id`) ) COMMENT = '博客点赞表';
INSERT INTO `points_account` (`user_id`, `balance`, `total_earned`, `total_spent`) VALUES (1, 500, 500, 0) ON DUPLICATE KEY UPDATE `balance` = `balance`;
INSERT INTO `points_product` (`id`, `name`, `description`, `image_url`, `cost_points`, `stock`, `status`) VALUES (2001, '书币月卡', '赠送 300 书币，30 天有效', NULL, 200, 100, 1), (2002, '墨阅定制书签', '金属书签一套', NULL, 150, 50, 1), (2003, '作者月度推荐位', '作品首页推荐 7 天', NULL, 800, 10, 1) ON DUPLICATE KEY UPDATE `name` = VALUES(`name`);
INSERT INTO `blog_post` (`id`, `author_id`, `title`, `cover_url`, `summary`, `content`, `status`, `like_count`, `comment_count`, `view_count`) VALUES (3001, 1, '我的写作心得：如何从零开始写一本小说', NULL, '分享三年创作路上的方法与踩坑。', '写作是一场马拉松，与其追求一天写一万字，不如先养成每天稳定的输出节奏……（正文示例）', 1, 12, 3, 240) ON DUPLICATE KEY UPDATE `title` = VALUES(`title`);

-- ============ V5__comment_like.sql ============
DROP TABLE IF EXISTS `comment_like`;
CREATE TABLE `comment_like` ( `id` BIGINT NOT NULL COMMENT '主键', `comment_id` BIGINT NOT NULL COMMENT '评论 ID → comment.id', `user_id` BIGINT NOT NULL COMMENT '点赞人 → user.id', `is_deleted` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除', `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间', `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间', PRIMARY KEY (`id`), UNIQUE KEY `comment_like_uk_comment_user` (`comment_id`, `user_id`), KEY `comment_like_idx_comment` (`comment_id`) ) COMMENT = '评论点赞表';

-- ============ V6__announcement_and_reward_fix.sql ============
ALTER TABLE `reward_order` ADD COLUMN `is_deleted` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除';
DROP TABLE IF EXISTS `announcement`;
CREATE TABLE `announcement` ( `id` BIGINT NOT NULL COMMENT '公告主键', `title` VARCHAR(128) NOT NULL COMMENT '标题', `content` TEXT NOT NULL COMMENT '正文', `type` TINYINT NOT NULL DEFAULT 1 COMMENT '类型：1 站内公告 / 2 活动 / 3 系统维护', `status` TINYINT NOT NULL DEFAULT 0 COMMENT '状态：0 草稿 / 1 已发布 / 2 已下线', `is_top` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否置顶：0 否 / 1 是', `publish_time` DATETIME DEFAULT NULL COMMENT '发布时间', `is_deleted` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除', `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间', `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间', PRIMARY KEY (`id`), KEY `announcement_idx_status` (`status`), KEY `announcement_idx_top_time` (`is_top`, `publish_time`) ) COMMENT = '运营公告表';

-- ============ V7__points_earning.sql ============
DROP TABLE IF EXISTS `points_check_in`;
CREATE TABLE `points_check_in` ( `id` BIGINT NOT NULL COMMENT '主键', `user_id` BIGINT NOT NULL COMMENT '用户 ID（主键之一）→ user.id', `check_in_date` DATE NOT NULL COMMENT '签到日期 YYYY-MM-DD', `points` INT NOT NULL DEFAULT 0 COMMENT '本次签到发放积分', `is_deleted` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除', `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '签到时间', `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间', PRIMARY KEY (`id`), UNIQUE KEY `points_check_in_uk_user_date` (`user_id`, `check_in_date`) ) COMMENT = '每日签到记录表';
DROP TABLE IF EXISTS `points_flow`;
CREATE TABLE `points_flow` ( `id` BIGINT NOT NULL COMMENT '主键', `user_id` BIGINT NOT NULL COMMENT '用户 ID → user.id', `biz_type` TINYINT NOT NULL COMMENT '业务类型：1 签到 / 2 阅读时长 / 3 评论奖励 / 4 系统发放 / 5 兑换消费', `points` INT NOT NULL COMMENT '积分变动（正获得 / 负消费）', `remark` VARCHAR(255) DEFAULT NULL COMMENT '备注', `is_deleted` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除', `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '发生时间', `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间', PRIMARY KEY (`id`), KEY `points_flow_idx_user` (`user_id`) ) COMMENT = '积分流水表（只增台账）';

-- ============ V8__merch_mall.sql ============
DROP TABLE IF EXISTS `merch_product`;
CREATE TABLE `merch_product` ( `id` BIGINT NOT NULL COMMENT '商品主键', `name` VARCHAR(128) NOT NULL COMMENT '商品名称', `description` VARCHAR(500) DEFAULT NULL COMMENT '商品描述', `image_url` VARCHAR(255) DEFAULT NULL COMMENT '商品图片', `price` DECIMAL(10,2) NOT NULL DEFAULT 0.00 COMMENT '售价（元）', `stock` INT NOT NULL DEFAULT 0 COMMENT '库存', `sales` INT NOT NULL DEFAULT 0 COMMENT '累计销量', `status` TINYINT NOT NULL DEFAULT 1 COMMENT '状态：1 上架 / 2 下架', `is_deleted` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除', `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间', `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间', PRIMARY KEY (`id`), KEY `merch_product_idx_status` (`status`) ) COMMENT = '周边商品表';
DROP TABLE IF EXISTS `merch_cart`;
CREATE TABLE `merch_cart` ( `id` BIGINT NOT NULL COMMENT '主键', `user_id` BIGINT NOT NULL COMMENT '用户 ID → user.id', `product_id` BIGINT NOT NULL COMMENT '商品 ID → merch_product.id', `quantity` INT NOT NULL DEFAULT 1 COMMENT '数量', `is_deleted` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除', `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '加入时间', `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间', PRIMARY KEY (`id`), UNIQUE KEY `merch_cart_uk_user_product` (`user_id`, `product_id`), KEY `merch_cart_idx_user` (`user_id`) ) COMMENT = '周边购物车表';
DROP TABLE IF EXISTS `merch_order`;
CREATE TABLE `merch_order` ( `id` BIGINT NOT NULL COMMENT '订单主键', `order_no` VARCHAR(32) NOT NULL COMMENT '订单号（一次结算一个，整单共用）', `user_id` BIGINT NOT NULL COMMENT '下单人 → user.id', `product_id` BIGINT NOT NULL COMMENT '商品 ID → merch_product.id', `product_name` VARCHAR(128) DEFAULT NULL COMMENT '商品名称快照', `quantity` INT NOT NULL DEFAULT 1 COMMENT '购买数量', `total_amount` DECIMAL(10,2) NOT NULL DEFAULT 0.00 COMMENT '本行金额（元）= price * quantity', `status` TINYINT NOT NULL DEFAULT 0 COMMENT '状态：0 待支付 / 1 已支付 / 2 已取消', `is_deleted` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除', `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '下单时间', `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间', PRIMARY KEY (`id`), KEY `merch_order_idx_order_no` (`order_no`), KEY `merch_order_idx_user` (`user_id`) ) COMMENT = '周边订单表（一行一商品）';

-- ============ V9__ai_assistant.sql ============
DROP TABLE IF EXISTS `ai_session`;
CREATE TABLE `ai_session` ( `id` BIGINT NOT NULL COMMENT '会话主键', `user_id` BIGINT NOT NULL COMMENT '用户 ID → user.id', `title` VARCHAR(128) DEFAULT NULL COMMENT '会话标题（默认取首条提问截断）', `is_deleted` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除', `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间', `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间', PRIMARY KEY (`id`), KEY `ai_session_idx_user` (`user_id`) ) COMMENT = 'AI 客服会话表';
DROP TABLE IF EXISTS `ai_message`;
CREATE TABLE `ai_message` ( `id` BIGINT NOT NULL COMMENT '消息主键', `session_id` BIGINT NOT NULL COMMENT '会话 ID → ai_session.id', `role` TINYINT NOT NULL DEFAULT 1 COMMENT '角色：1 用户 / 2 助手', `content` VARCHAR(2000) NOT NULL COMMENT '消息内容', `is_deleted` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除', `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '发送时间', `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间', PRIMARY KEY (`id`), KEY `ai_message_idx_session` (`session_id`) ) COMMENT = 'AI 客服消息表';

-- ============ V10__audit_remark.sql ============
ALTER TABLE audit_task ADD COLUMN remark VARCHAR(255) NULL COMMENT '审核意见（通过/驳回理由，可空）';
ALTER TABLE audit_task ADD COLUMN operator_id BIGINT NULL COMMENT '审核操作人用户 ID（网关注入，可空）';

-- ============ V11__book_finish_apply.sql ============
CREATE TABLE IF NOT EXISTS `book_finish_apply` ( `id` BIGINT NOT NULL COMMENT '申请主键（雪花 ID）', `book_id` BIGINT NOT NULL COMMENT '作品 ID → book.id', `author_id` BIGINT NOT NULL COMMENT '申请人（作者）ID → user.id', `reason` VARCHAR(500) DEFAULT NULL COMMENT '完结申请理由（可空）', `status` TINYINT NOT NULL DEFAULT 0 COMMENT '审核状态：0 待审核 / 1 通过 / 2 驳回', `auditor_id` BIGINT DEFAULT NULL COMMENT '审核人（管理员）ID → user.id', `audit_remark` VARCHAR(255) DEFAULT NULL COMMENT '审核意见（通过 / 驳回理由，可空）', `is_deleted` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除：0 否 / 1 是', `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间', `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间', PRIMARY KEY (`id`), KEY `book_finish_apply_idx_book_status` (`book_id`, `status`), KEY `book_finish_apply_idx_status_create` (`status`, `create_time`) ) COMMENT = '作品完结申请表';

-- ============ V12__system_management.sql ============
CREATE TABLE IF NOT EXISTS `sys_dept` ( `id` BIGINT NOT NULL COMMENT '部门主键（雪花 ID）', `parent_id` BIGINT NOT NULL DEFAULT 0 COMMENT '父部门 ID，0 表示顶级', `dept_name` VARCHAR(50) NOT NULL COMMENT '部门名称', `order_num` INT NOT NULL DEFAULT 0 COMMENT '显示顺序', `leader` VARCHAR(20) DEFAULT NULL COMMENT '负责人', `phone` VARCHAR(11) DEFAULT NULL COMMENT '联系电话', `email` VARCHAR(64) DEFAULT NULL COMMENT '邮箱', `status` TINYINT NOT NULL DEFAULT 1 COMMENT '状态：0 禁用 / 1 正常', `is_deleted` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除：0 否 / 1 是', `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间', `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间', PRIMARY KEY (`id`), KEY `sys_dept_idx_parent` (`parent_id`) ) COMMENT = '系统部门表';
CREATE TABLE IF NOT EXISTS `sys_user` ( `id` BIGINT NOT NULL COMMENT '用户主键（雪花 ID）', `dept_id` BIGINT NOT NULL DEFAULT 0 COMMENT '部门 ID → sys_dept.id，0 未分配', `username` VARCHAR(30) NOT NULL COMMENT '登录账号', `nickname` VARCHAR(30) NOT NULL COMMENT '昵称', `password` VARCHAR(72) NOT NULL COMMENT 'BCrypt 密码哈希', `email` VARCHAR(64) DEFAULT NULL COMMENT '邮箱', `phone` VARCHAR(11) DEFAULT NULL COMMENT '手机号', `status` TINYINT NOT NULL DEFAULT 1 COMMENT '状态：0 禁用 / 1 正常', `is_deleted` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除：0 否 / 1 是', `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间', `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间', PRIMARY KEY (`id`), UNIQUE KEY `sys_user_uk_username` (`username`), KEY `sys_user_idx_dept` (`dept_id`), KEY `sys_user_idx_status` (`status`) ) COMMENT = '系统用户表（运营后台操作员）';
CREATE TABLE IF NOT EXISTS `sys_role` ( `id` BIGINT NOT NULL COMMENT '角色主键（雪花 ID）', `role_name` VARCHAR(30) NOT NULL COMMENT '角色名称', `role_key` VARCHAR(50) NOT NULL COMMENT '角色标识（权限校验用，如 admin）', `data_scope` TINYINT NOT NULL DEFAULT 1 COMMENT '数据权限：1 全部 / 2 自定义部门 / 3 仅本人', `dept_ids` VARCHAR(255) DEFAULT NULL COMMENT '自定义数据权限部门 ID，逗号分隔（data_scope=2）', `status` TINYINT NOT NULL DEFAULT 1 COMMENT '状态：0 禁用 / 1 正常', `is_deleted` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除：0 否 / 1 是', `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间', `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间', PRIMARY KEY (`id`), UNIQUE KEY `sys_role_uk_role_key` (`role_key`), KEY `sys_role_idx_status` (`status`) ) COMMENT = '系统角色表';
CREATE TABLE IF NOT EXISTS `sys_menu` ( `id` BIGINT NOT NULL COMMENT '菜单主键（雪花 ID）', `parent_id` BIGINT NOT NULL DEFAULT 0 COMMENT '父菜单 ID，0 表示顶级', `menu_name` VARCHAR(50) NOT NULL COMMENT '菜单名称', `menu_type` TINYINT NOT NULL DEFAULT 1 COMMENT '类型：0 目录 / 1 菜单 / 2 按钮', `path` VARCHAR(128) DEFAULT NULL COMMENT '路由地址', `component` VARCHAR(128) DEFAULT NULL COMMENT '前端组件路径', `perms` VARCHAR(128) DEFAULT NULL COMMENT '权限标识（按钮级，如 system:user:add）', `icon` VARCHAR(64) DEFAULT NULL COMMENT '图标', `order_num` INT NOT NULL DEFAULT 0 COMMENT '显示顺序', `status` TINYINT NOT NULL DEFAULT 1 COMMENT '状态：0 禁用 / 1 正常', `is_deleted` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除：0 否 / 1 是', `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间', `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间', PRIMARY KEY (`id`), KEY `sys_menu_idx_parent` (`parent_id`) ) COMMENT = '系统菜单表（目录/菜单/按钮）';
CREATE TABLE IF NOT EXISTS `sys_user_role` ( `user_id` BIGINT NOT NULL COMMENT '用户 ID → sys_user.id', `role_id` BIGINT NOT NULL COMMENT '角色 ID → sys_role.id', PRIMARY KEY (`user_id`, `role_id`), KEY `sys_user_role_idx_role` (`role_id`) ) COMMENT = '用户-角色关联表';
CREATE TABLE IF NOT EXISTS `sys_role_menu` ( `role_id` BIGINT NOT NULL COMMENT '角色 ID → sys_role.id', `menu_id` BIGINT NOT NULL COMMENT '菜单 ID → sys_menu.id', PRIMARY KEY (`role_id`, `menu_id`), KEY `sys_role_menu_idx_menu` (`menu_id`) ) COMMENT = '角色-菜单关联表';

-- ============ V13__content_safety_and_reach.sql ============
CREATE TABLE IF NOT EXISTS `sensitive_word` ( `id` BIGINT NOT NULL COMMENT '主键（雪花 ID）', `word` VARCHAR(64) NOT NULL COMMENT '敏感词', `level` TINYINT NOT NULL DEFAULT 1 COMMENT '等级：1 拦截 / 2 告警（转人工）', `category` VARCHAR(32) DEFAULT NULL COMMENT '分类：政治/广告/谩骂/涉黄…', `status` TINYINT NOT NULL DEFAULT 1 COMMENT '状态：0 停用 / 1 启用', `is_deleted` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除', `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, PRIMARY KEY (`id`), UNIQUE KEY `sensitive_word_uk_word` (`word`), KEY `sensitive_word_idx_status_level` (`status`, `level`) ) COMMENT='敏感词库';
CREATE TABLE IF NOT EXISTS `report` ( `id` BIGINT NOT NULL COMMENT '举报主键（雪花 ID）', `reporter_id` BIGINT NOT NULL COMMENT '举报人 → user.id', `target_type` TINYINT NOT NULL COMMENT '对象：1 书籍 / 2 章节 / 3 评论 / 4 用户', `target_id` BIGINT NOT NULL COMMENT '对象主键', `reason_type` TINYINT NOT NULL DEFAULT 1 COMMENT '原因：1 违规内容 / 2 广告 / 3 侵权 / 4 其他', `reason` VARCHAR(500) DEFAULT NULL COMMENT '补充说明', `status` TINYINT NOT NULL DEFAULT 0 COMMENT '状态：0 待处理 / 1 属实 / 2 驳回', `handler_id` BIGINT DEFAULT NULL COMMENT '处理人 → 管理员 ID', `handle_remark` VARCHAR(255) DEFAULT NULL COMMENT '处理意见', `handle_time` DATETIME DEFAULT NULL COMMENT '处理时间', `is_deleted` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除', `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, PRIMARY KEY (`id`), KEY `report_idx_status` (`status`), KEY `report_idx_target` (`target_type`, `target_id`), KEY `report_idx_reporter` (`reporter_id`) ) COMMENT='举报表';
CREATE TABLE IF NOT EXISTS `message_template` ( `id` BIGINT NOT NULL, `code` VARCHAR(64) NOT NULL COMMENT '模板编码，如 AUDIT_PASS / REPORT_RESULT', `name` VARCHAR(64) NOT NULL COMMENT '模板名称', `title_tpl` VARCHAR(255) DEFAULT NULL COMMENT '标题模板，占位符 {param}', `content_tpl` VARCHAR(1000) NOT NULL COMMENT '内容模板', `channels` VARCHAR(64) NOT NULL DEFAULT '1' COMMENT '默认渠道，逗号分隔：1 站内信/2 邮件/3 短信/4 推送', `status` TINYINT NOT NULL DEFAULT 1 COMMENT '状态：0 停用 / 1 启用', `is_deleted` TINYINT(1) NOT NULL DEFAULT 0, `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, PRIMARY KEY (`id`), UNIQUE KEY `message_template_uk_code` (`code`) ) COMMENT='消息模板表';
CREATE TABLE IF NOT EXISTS `message_channel_record` ( `id` BIGINT NOT NULL, `user_id` BIGINT NOT NULL COMMENT '接收用户 → user.id', `channel` TINYINT NOT NULL COMMENT '渠道：1 站内信/2 邮件/3 短信/4 推送', `template_code` VARCHAR(64) DEFAULT NULL COMMENT '模板编码', `target` VARCHAR(128) DEFAULT NULL COMMENT '投递地址（邮箱/手机号）', `title` VARCHAR(128) DEFAULT NULL, `content` VARCHAR(1000) DEFAULT NULL, `biz_type` VARCHAR(64) DEFAULT NULL COMMENT '业务类型，如 AUDIT / REPORT', `biz_id` BIGINT DEFAULT NULL COMMENT '业务主键', `status` TINYINT NOT NULL DEFAULT 0 COMMENT '0 待发 / 1 成功 / 2 失败', `error_msg` VARCHAR(255) DEFAULT NULL, `retry_count` INT NOT NULL DEFAULT 0, `send_time` DATETIME DEFAULT NULL, `is_deleted` TINYINT(1) NOT NULL DEFAULT 0, `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, PRIMARY KEY (`id`), KEY `message_channel_record_idx_user` (`user_id`), KEY `message_channel_record_idx_status` (`status`), KEY `message_channel_record_idx_template` (`template_code`) ) COMMENT='消息触达记录表';
INSERT IGNORE INTO `sensitive_word` (`id`,`word`,`level`,`category`) VALUES (910000000000000001,'示例敏感词A',1,'政治'), (910000000000000002,'示例敏感词B',1,'广告'), (910000000000000003,'示例灰词C',2,'谩骂');
INSERT IGNORE INTO `message_template` (`id`,`code`,`name`,`title_tpl`,`content_tpl`,`channels`) VALUES (920000000000000001,'AUDIT_PASS','审核通过','{bizName}审核通过','您提交的{bizName}已通过审核。','1,2'), (920000000000000002,'AUDIT_REJECT','审核驳回','{bizName}审核驳回','您提交的{bizName}未通过审核：{reason}','1,2'), (920000000000000003,'REPORT_RESULT','举报处理结果','您的举报已处理','您对{targetDesc}的举报处理结果：{result}。','1,2');

-- ============ V14__system_dict_config_log.sql ============
CREATE TABLE IF NOT EXISTS `sys_dict_type` ( `id` BIGINT NOT NULL COMMENT '字典类型主键（雪花 ID）', `dict_name` VARCHAR(50) NOT NULL COMMENT '字典名称，如 小说状态', `dict_type` VARCHAR(100) NOT NULL COMMENT '字典类型编码，如 novel_status', `status` TINYINT NOT NULL DEFAULT 1 COMMENT '状态：0 停用 / 1 启用', `remark` VARCHAR(255) DEFAULT NULL COMMENT '备注', `is_deleted` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除：0 否 / 1 是', `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间', `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间', PRIMARY KEY (`id`), UNIQUE KEY `sys_dict_type_uk_dict_type` (`dict_type`) ) COMMENT = '字典类型表';
CREATE TABLE IF NOT EXISTS `sys_dict_data` ( `id` BIGINT NOT NULL COMMENT '字典数据主键（雪花 ID）', `dict_type` VARCHAR(100) NOT NULL COMMENT '所属字典类型编码 → sys_dict_type.dict_type', `dict_label` VARCHAR(100) NOT NULL COMMENT '字典标签（展示用）', `dict_value` VARCHAR(100) NOT NULL COMMENT '字典键值（存储用）', `dict_sort` INT NOT NULL DEFAULT 0 COMMENT '显示顺序', `is_default` TINYINT NOT NULL DEFAULT 0 COMMENT '是否默认：0 否 / 1 是', `status` TINYINT NOT NULL DEFAULT 1 COMMENT '状态：0 停用 / 1 启用', `remark` VARCHAR(255) DEFAULT NULL COMMENT '备注', `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间', `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间', PRIMARY KEY (`id`), KEY `sys_dict_data_idx_dict_type` (`dict_type`) ) COMMENT = '字典数据表';
CREATE TABLE IF NOT EXISTS `sys_config` ( `id` BIGINT NOT NULL COMMENT '参数主键（雪花 ID）', `config_name` VARCHAR(100) NOT NULL COMMENT '参数名称，如 默认章节字数', `config_key` VARCHAR(100) NOT NULL COMMENT '参数键名，如 system.chapter.word-count', `config_value` VARCHAR(500) DEFAULT NULL COMMENT '参数键值', `is_system` TINYINT NOT NULL DEFAULT 0 COMMENT '是否内置参数：0 否 / 1 是（内置不可删除）', `remark` VARCHAR(255) DEFAULT NULL COMMENT '备注', `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间', `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间', PRIMARY KEY (`id`), UNIQUE KEY `sys_config_uk_config_key` (`config_key`) ) COMMENT = '系统参数配置表';
CREATE TABLE IF NOT EXISTS `sys_oper_log` ( `id` BIGINT NOT NULL COMMENT '日志主键（雪花 ID）', `module` VARCHAR(50) DEFAULT NULL COMMENT '业务模块，如 字典管理', `business_type` TINYINT NOT NULL DEFAULT 0 COMMENT '业务类型：0 其它 / 1 新增 / 2 修改 / 3 删除 / 4 导出 / 5 强退 / 6 生成代码', `request_method` VARCHAR(10) DEFAULT NULL COMMENT 'HTTP 请求方式：GET/POST/PUT/DELETE', `url` VARCHAR(255) DEFAULT NULL COMMENT '请求 URL', `operator_id` BIGINT DEFAULT NULL COMMENT '操作人员 ID → sys_user.id', `operator_name` VARCHAR(50) DEFAULT NULL COMMENT '操作人员名称', `ip` VARCHAR(64) DEFAULT NULL COMMENT '操作 IP', `param` TEXT DEFAULT NULL COMMENT '请求参数（截断 2000 字符）', `result` TEXT DEFAULT NULL COMMENT '返回结果（截断 2000 字符）', `status` TINYINT NOT NULL DEFAULT 0 COMMENT '操作状态：0 成功 / 1 失败', `error_msg` TEXT DEFAULT NULL COMMENT '错误信息', `cost_ms` INT DEFAULT NULL COMMENT '耗时（毫秒）', `oper_time` DATETIME DEFAULT NULL COMMENT '操作时间', PRIMARY KEY (`id`), KEY `sys_oper_log_idx_operator` (`operator_id`), KEY `sys_oper_log_idx_module` (`module`), KEY `sys_oper_log_idx_oper_time` (`oper_time`) ) COMMENT = '操作日志表';
CREATE TABLE IF NOT EXISTS `sys_logininfor` ( `id` BIGINT NOT NULL COMMENT '日志主键（雪花 ID）', `username` VARCHAR(50) DEFAULT NULL COMMENT '登录账号', `ip` VARCHAR(64) DEFAULT NULL COMMENT '登录 IP', `user_agent` VARCHAR(255) DEFAULT NULL COMMENT '浏览器 UA', `status` TINYINT NOT NULL DEFAULT 0 COMMENT '登录状态：0 成功 / 1 失败', `msg` VARCHAR(255) DEFAULT NULL COMMENT '提示信息，如 登录成功 / 账号或密码错误', `login_time` DATETIME DEFAULT NULL COMMENT '登录时间', PRIMARY KEY (`id`), KEY `sys_logininfor_idx_username` (`username`), KEY `sys_logininfor_idx_login_time` (`login_time`) ) COMMENT = '系统登录日志表';
INSERT IGNORE INTO `sys_config` (`id`, `config_name`, `config_key`, `config_value`, `is_system`, `remark`) VALUES (940000000000000001, '默认章节字数下限', 'system.chapter.min-word-count', '1000', 1, '发布章节的最小字数校验阈值'), (940000000000000002, '打赏单笔金额上限', 'system.reward.max-amount', '10000', 1, '单笔打赏允许的最大金额（元）');
INSERT IGNORE INTO `sys_dict_type` (`id`, `dict_name`, `dict_type`, `status`, `remark`) VALUES (940000000000000101, '小说状态', 'novel_status', 1, '书籍/小说发布状态字典'), (940000000000000102, '小说类型', 'novel_type', 1, '小说题材分类字典'), (940000000000000103, '公告类型', 'announcement_type', 1, '平台公告类型字典');
INSERT IGNORE INTO `sys_dict_data` (`id`, `dict_type`, `dict_label`, `dict_value`, `dict_sort`, `is_default`, `status`, `remark`) VALUES (940000000000000201, 'novel_status', '连载中', '1', 1, 1, 1, '状态 1：连载'), (940000000000000202, 'novel_status', '已完结', '2', 2, 0, 1, '状态 2：完结'), (940000000000000203, 'novel_status', '已下架', '0', 3, 0, 1, '状态 0：下架'), (940000000000000204, 'novel_type', '玄幻', '1', 1, 1, 1, '题材 1：玄幻'), (940000000000000205, 'novel_type', '都市', '2', 2, 0, 1, '题材 2：都市'), (940000000000000206, 'novel_type', '悬疑', '3', 3, 0, 1, '题材 3：悬疑'), (940000000000000207, 'announcement_type', '系统公告', '1', 1, 1, 1, '平台级系统公告'), (940000000000000208, 'announcement_type', '活动公告', '2', 2, 0, 1, '运营活动公告'), (940000000000000209, 'announcement_type', '维护公告', '3', 3, 0, 1, '停机维护公告');
INSERT IGNORE INTO `sys_menu` (`id`, `parent_id`, `menu_name`, `menu_type`, `path`, `component`, `perms`, `icon`, `order_num`, `status`) VALUES (940000000000001001, 0, '系统管理', 0, 'system', NULL, NULL, 'system', 1, 1), (940000000000001002, 0, '系统监控', 0, 'monitor', NULL, NULL, 'monitor', 2, 1), (940000000000001003, 0, '开发管理', 0, 'tool', NULL, NULL, 'tool', 3, 1), (940000000000001101, 940000000000001001, '字典管理', 1, 'dict', 'system/dict/index', NULL, 'dict', 1, 1), (940000000000001102, 940000000000001001, '参数设置', 1, 'config', 'system/config/index', NULL, 'edit', 2, 1), (940000000000001201, 940000000000001002, '操作日志', 1, 'operlog', 'monitor/operlog/index', NULL, 'form', 1, 1), (940000000000001202, 940000000000001002, '登录日志', 1, 'logininfor', 'monitor/logininfor/index', NULL, 'form', 2, 1), (940000000000001203, 940000000000001002, '在线用户', 1, 'online', 'monitor/online/index', NULL, 'user', 3, 1), (940000000000001204, 940000000000001002, '服务监控', 1, 'server', 'monitor/server/index', NULL, 'dashboard',4, 1), (940000000000001205, 940000000000001002, '数据监控', 1, 'dbpool', 'monitor/dbpool/index', NULL, 'chart', 5, 1), (940000000000001206, 940000000000001002, '定时任务', 1, 'job', 'monitor/job/index', NULL, 'job', 6, 1), (940000000000001301, 940000000000001003, '代码生成', 1, 'gen', 'tool/gen/index', NULL, 'code', 1, 1);
INSERT IGNORE INTO `sys_menu` (`id`, `parent_id`, `menu_name`, `menu_type`, `path`, `component`, `perms`, `icon`, `order_num`, `status`) VALUES (940000000000002101, 940000000000001101, '字典查询', 2, NULL, NULL, 'system:dict:list', NULL, 1, 1), (940000000000002102, 940000000000001101, '字典新增', 2, NULL, NULL, 'system:dict:add', NULL, 2, 1), (940000000000002103, 940000000000001101, '字典修改', 2, NULL, NULL, 'system:dict:edit', NULL, 3, 1), (940000000000002104, 940000000000001101, '字典删除', 2, NULL, NULL, 'system:dict:remove', NULL, 4, 1), (940000000000002105, 940000000000001101, '字典刷新', 2, NULL, NULL, 'system:dict:refresh', NULL, 5, 1), (940000000000002111, 940000000000001102, '参数查询', 2, NULL, NULL, 'system:config:list', NULL, 1, 1), (940000000000002112, 940000000000001102, '参数新增', 2, NULL, NULL, 'system:config:add', NULL, 2, 1), (940000000000002113, 940000000000001102, '参数修改', 2, NULL, NULL, 'system:config:edit', NULL, 3, 1), (940000000000002114, 940000000000001102, '参数删除', 2, NULL, NULL, 'system:config:remove', NULL, 4, 1), (940000000000002115, 940000000000001102, '参数刷新', 2, NULL, NULL, 'system:config:refresh', NULL, 5, 1), (940000000000002121, 940000000000001201, '操作日志查询', 2, NULL, NULL, 'system:operlog:list', NULL, 1, 1), (940000000000002122, 940000000000001201, '操作日志删除', 2, NULL, NULL, 'system:operlog:remove', NULL, 2, 1), (940000000000002131, 940000000000001202, '登录日志查询', 2, NULL, NULL, 'system:logininfor:list', NULL, 1, 1), (940000000000002132, 940000000000001202, '登录日志删除', 2, NULL, NULL, 'system:logininfor:remove', NULL, 2, 1), (940000000000002133, 940000000000001202, '登录日志清空', 2, NULL, NULL, 'system:logininfor:clear', NULL, 3, 1), (940000000000002141, 940000000000001203, '在线用户查询', 2, NULL, NULL, 'system:online:list', NULL, 1, 1), (940000000000002142, 940000000000001203, '在线用户强退', 2, NULL, NULL, 'system:online:forceLogout', NULL, 2, 1), (940000000000002151, 940000000000001204, '服务监控查询', 2, NULL, NULL, 'system:monitor:list', NULL, 1, 1), (940000000000002152, 940000000000001205, '数据监控查询', 2, NULL, NULL, 'system:monitor:list', NULL, 1, 1), (940000000000002161, 940000000000001206, '任务查询', 2, NULL, NULL, 'system:job:list', NULL, 1, 1), (940000000000002162, 940000000000001206, '任务新增', 2, NULL, NULL, 'system:job:add', NULL, 2, 1), (940000000000002163, 940000000000001206, '任务修改', 2, NULL, NULL, 'system:job:edit', NULL, 3, 1), (940000000000002164, 940000000000001206, '任务删除', 2, NULL, NULL, 'system:job:remove', NULL, 4, 1), (940000000000002165, 940000000000001206, '任务启停', 2, NULL, NULL, 'system:job:changeStatus', NULL, 5, 1), (940000000000002166, 940000000000001206, '任务执行', 2, NULL, NULL, 'system:job:run', NULL, 6, 1), (940000000000002171, 940000000000001301, '生成查询', 2, NULL, NULL, 'system:gen:list', NULL, 1, 1), (940000000000002172, 940000000000001301, '生成预览', 2, NULL, NULL, 'system:gen:preview', NULL, 2, 1), (940000000000002173, 940000000000001301, '生成下载', 2, NULL, NULL, 'system:gen:download', NULL, 3, 1);

-- ============ V15__risk_hit_count_and_risk_menus.sql ============
ALTER TABLE `sensitive_word` ADD COLUMN `hit_count` INT NOT NULL DEFAULT 0 COMMENT '命中次数统计（机审命中累计）';
INSERT IGNORE INTO `sys_menu` (`id`, `parent_id`, `menu_name`, `menu_type`, `path`, `component`, `perms`, `icon`, `order_num`, `status`) VALUES (940000000000001004, 0, '内容安全', 0, 'safety', NULL, NULL, 'safe', 4, 1), (940000000000001401, 940000000000001004, '敏感词管理', 1, 'sensitiveword', 'risk/word/index', NULL, 'edit', 1, 1), (940000000000001402, 940000000000001004, '举报管理', 1, 'report', 'risk/report/index', NULL, 'form', 2, 1);
INSERT IGNORE INTO `sys_menu` (`id`, `parent_id`, `menu_name`, `menu_type`, `path`, `component`, `perms`, `icon`, `order_num`, `status`) VALUES (940000000000002181, 940000000000001401, '敏感词查询', 2, NULL, NULL, 'system:risk:word:list', NULL, 1, 1), (940000000000002182, 940000000000001401, '敏感词新增', 2, NULL, NULL, 'system:risk:word:add', NULL, 2, 1), (940000000000002183, 940000000000001401, '敏感词修改', 2, NULL, NULL, 'system:risk:word:edit', NULL, 3, 1), (940000000000002184, 940000000000001401, '敏感词删除', 2, NULL, NULL, 'system:risk:word:remove', NULL, 4, 1), (940000000000002185, 940000000000001401, '敏感词导入', 2, NULL, NULL, 'system:risk:word:import', NULL, 5, 1), (940000000000002186, 940000000000001401, '敏感词导出', 2, NULL, NULL, 'system:risk:word:export', NULL, 6, 1), (940000000000002187, 940000000000001401, '敏感词词库刷新', 2, NULL, NULL, 'system:risk:word:refresh', NULL, 7, 1), (940000000000002191, 940000000000001402, '举报查询', 2, NULL, NULL, 'system:report:list', NULL, 1, 1), (940000000000002192, 940000000000001402, '举报处理', 2, NULL, NULL, 'system:report:handle', NULL, 2, 1);

-- ============ V16__settlement.sql ============
CREATE TABLE `settlement_order` ( `id` BIGINT NOT NULL COMMENT '结算单ID（雪花ID）', `author_id` BIGINT NOT NULL COMMENT '作者ID', `period` VARCHAR(20) NOT NULL COMMENT '结算月份 YYYY-MM', `total_amount` DECIMAL(12,2) NOT NULL DEFAULT 0 COMMENT '结算总额（元）', `status` TINYINT NOT NULL DEFAULT 0 COMMENT '0待结算/1已结算待打款/2已打款/3打款失败', `pay_channel` TINYINT NULL COMMENT '打款渠道 1微信/2支付宝', `pay_serial` VARCHAR(64) NULL COMMENT '渠道流水号（幂等键）', `remark` VARCHAR(255) NULL COMMENT '审核/打款备注', `operator_id` BIGINT NULL COMMENT '审核/打款操作人', `create_time` DATETIME NULL COMMENT '创建时间', `update_time` DATETIME NULL COMMENT '更新时间', `is_deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除 0否/1是', PRIMARY KEY (`id`), KEY `settlement_order_idx_settlement_author_period` (`author_id`, `period`), KEY `settlement_order_idx_settlement_status` (`status`) ) COMMENT='稿酬结算单';
ALTER TABLE `author_income` ADD COLUMN `settlement_id` BIGINT NULL COMMENT '结算单ID（锁定已结算流水）';

-- ============ V17__risk_owner_notice_and_dashboard.sql ============
INSERT IGNORE INTO `message_template` (`id`,`code`,`name`,`title_tpl`,`content_tpl`,`channels`) VALUES (920000000000000004,'OWNER_NOTICE','被处理方通知','{targetDesc}处理通知','您发布的{targetDesc}因被举报，平台处理结果：{result}。处理意见：{reason}','1');
INSERT IGNORE INTO `sys_menu` (`id`, `parent_id`, `menu_name`, `menu_type`, `path`, `component`, `perms`, `icon`, `order_num`, `status`) VALUES (940000000000002193, 940000000000001004, '风险看板', 2, NULL, NULL, 'system:risk:dashboard', 'form', 3, 1);

-- ============ V18__user_contact.sql ============
ALTER TABLE `user` ADD COLUMN `email` VARCHAR(128) DEFAULT NULL COMMENT '邮箱（触达渠道：邮件；可空）';
ALTER TABLE `user` ADD COLUMN `device_token` VARCHAR(512) DEFAULT NULL COMMENT '设备推送令牌（触达渠道：推送；可空）';

-- ============ V19__bookshelf_listen_progress.sql ============
ALTER TABLE `bookshelf` ADD COLUMN `listen_chapter_id` BIGINT DEFAULT NULL COMMENT '听书进度：当前收听章节 → chapter.id';
ALTER TABLE `bookshelf` ADD COLUMN `listen_segment_index` INT DEFAULT 0 COMMENT '听书进度：章节内片段序号（断点续听）';
ALTER TABLE `bookshelf` ADD COLUMN `listen_char_offset` INT DEFAULT 0 COMMENT '听书进度：片段内字符偏移';

-- ============ V20__category.sql ============
CREATE TABLE IF NOT EXISTS `category` ( `id` BIGINT NOT NULL COMMENT '分类主键（雪花 ID）', `name` VARCHAR(50) NOT NULL COMMENT '分类名称', `icon` VARCHAR(64) DEFAULT NULL COMMENT '分类图标（前端展示用）', `sort` INT NOT NULL DEFAULT 0 COMMENT '显示顺序（升序：书城筛选项排序）', `status` TINYINT DEFAULT 1 COMMENT '状态：0 禁用 / 1 正常', `is_deleted` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除：0 否 / 1 是（@TableLogic）', `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间', `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间', PRIMARY KEY (`id`) ) COMMENT = '小说分类表（运营后台可增删改排序）';

-- ============ V21__category_seed.sql ============
INSERT INTO category (id, name, icon, sort, status) SELECT 1, '玄幻', 'fantasy', 1, 1 WHERE NOT EXISTS (SELECT 1 FROM category WHERE id = 1);
INSERT INTO category (id, name, icon, sort, status) SELECT 2, '都市', 'city', 2, 1 WHERE NOT EXISTS (SELECT 1 FROM category WHERE id = 2);
INSERT INTO category (id, name, icon, sort, status) SELECT 3, '悬疑', 'mystery', 3, 1 WHERE NOT EXISTS (SELECT 1 FROM category WHERE id = 3);
INSERT INTO sys_menu (id, parent_id, menu_name, menu_type, path, component, perms, icon, order_num, status) SELECT 940000000000003001, 0, '分类管理', 1, 'category', 'content/category/index', 'system:category:list', 'category', 5, 1 WHERE NOT EXISTS (SELECT 1 FROM sys_menu WHERE id = 940000000000003001);
INSERT INTO sys_menu (id, parent_id, menu_name, menu_type, path, component, perms, icon, order_num, status) SELECT 940000000000003011, 940000000000003001, '分类查询', 2, NULL, NULL, 'system:category:list', NULL, 1, 1 WHERE NOT EXISTS (SELECT 1 FROM sys_menu WHERE id = 940000000000003011);
INSERT INTO sys_menu (id, parent_id, menu_name, menu_type, path, component, perms, icon, order_num, status) SELECT 940000000000003012, 940000000000003001, '分类新增', 2, NULL, NULL, 'system:category:add', NULL, 2, 1 WHERE NOT EXISTS (SELECT 1 FROM sys_menu WHERE id = 940000000000003012);
INSERT INTO sys_menu (id, parent_id, menu_name, menu_type, path, component, perms, icon, order_num, status) SELECT 940000000000003013, 940000000000003001, '分类修改', 2, NULL, NULL, 'system:category:edit', NULL, 3, 1 WHERE NOT EXISTS (SELECT 1 FROM sys_menu WHERE id = 940000000000003013);
INSERT INTO sys_menu (id, parent_id, menu_name, menu_type, path, component, perms, icon, order_num, status) SELECT 940000000000003014, 940000000000003001, '分类删除', 2, NULL, NULL, 'system:category:remove', NULL, 4, 1 WHERE NOT EXISTS (SELECT 1 FROM sys_menu WHERE id = 940000000000003014);

-- ============ V22__follow_and_dynamic.sql ============
CREATE TABLE IF NOT EXISTS `follow_relation` ( `id` BIGINT NOT NULL COMMENT '主键（雪花 ID）', `fan_id` BIGINT NOT NULL COMMENT '粉丝（关注发起方）ID → user.id', `author_id` BIGINT NOT NULL COMMENT '被关注作者 ID → user.id', `is_deleted` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除：0 否 / 1 是', `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间', `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间', PRIMARY KEY (`id`), UNIQUE KEY `follow_relation_uk_follow_pair` (`fan_id`, `author_id`), KEY `follow_relation_idx_follow_author` (`author_id`), KEY `follow_relation_idx_follow_fan` (`fan_id`), KEY `follow_relation_idx_follow_create` (`create_time`) ) COMMENT = '关注关系表';
CREATE TABLE IF NOT EXISTS `user_dynamic` ( `id` BIGINT NOT NULL COMMENT '主键（雪花 ID）', `actor_user_id` BIGINT DEFAULT NULL COMMENT '动作发起者（打赏者 / 作者本人）ID → user.id', `actor_name` VARCHAR(64) DEFAULT NULL COMMENT '反规范化快照：动作发起者昵称', `author_id` BIGINT NOT NULL COMMENT '动态归属作者（进粉丝流的人）→ user.id', `author_name` VARCHAR(64) DEFAULT NULL COMMENT '反规范化快照：作者昵称', `book_id` BIGINT DEFAULT NULL COMMENT '关联作品 ID → book.id', `book_title` VARCHAR(128) DEFAULT NULL COMMENT '反规范化快照：作品标题', `dynamic_type` TINYINT NOT NULL COMMENT '动态类型：1 发布新作 / 2 作品完结 / 3 打赏 / 4 关注(预留)', `summary` VARCHAR(255) DEFAULT NULL COMMENT '可选补充文案（后端不拼全文，前端按 type+字段渲染）', `ref_id` BIGINT DEFAULT NULL COMMENT '来源业务主键（bookId / rewardOrderId）', `ref_type` TINYINT NOT NULL COMMENT '来源类型：1=book发布 / 2=reward订单', `is_deleted` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除：0 否 / 1 是', `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '排序键', `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间', PRIMARY KEY (`id`), UNIQUE KEY `user_dynamic_uk_dynamic_ref` (`ref_type`, `ref_id`), KEY `user_dynamic_idx_dynamic_actor` (`actor_user_id`), KEY `user_dynamic_idx_dynamic_author` (`author_id`), KEY `user_dynamic_idx_dynamic_create` (`create_time`) ) COMMENT = '用户动态表（关注流时间线 / 作者主页动态）';

-- ============ V23__member_subscription.sql ============
CREATE TABLE IF NOT EXISTS `member_tier` ( `id` BIGINT NOT NULL COMMENT '主键（雪花 ID）', `tier_code` VARCHAR(32) NOT NULL COMMENT '套餐编码（全局唯一，如 MONTHLY_BASIC）', `tier_name` VARCHAR(64) NOT NULL COMMENT '套餐名称', `monthly_price` DECIMAL(10,2) NOT NULL DEFAULT 0.00 COMMENT '包月价格（元）', `duration_days` INT NOT NULL DEFAULT 30 COMMENT '有效期天数', `ad_free` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '免广告权益：0 否 / 1 是', `discount_rate` DECIMAL(4,2) NOT NULL DEFAULT 1.00 COMMENT '折扣率（1.00 无折扣，0.90=9 折）', `badge` VARCHAR(64) DEFAULT NULL COMMENT '专属徽章名', `sort` INT NOT NULL DEFAULT 0 COMMENT '展示排序', `is_deleted` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除：0 否 / 1 是', `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间', `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间', PRIMARY KEY (`id`), UNIQUE KEY `member_tier_uk_member_tier_code` (`tier_code`), KEY `member_tier_idx_member_tier_sort` (`sort`) ) COMMENT = '会员套餐配置表';
CREATE TABLE IF NOT EXISTS `member_subscription` ( `id` BIGINT NOT NULL COMMENT '主键（雪花 ID）', `user_id` BIGINT NOT NULL COMMENT '订阅用户 ID → user.id', `tier_code` VARCHAR(32) NOT NULL COMMENT '套餐编码 → member_tier.tier_code', `tier_name` VARCHAR(64) DEFAULT NULL COMMENT '反规范化快照：套餐名称', `status` TINYINT NOT NULL DEFAULT 0 COMMENT '订阅状态：0 待支付 / 1 生效中 / 2 已过期 / 3 已取消', `start_time` DATETIME DEFAULT NULL COMMENT '生效开始时间', `end_time` DATETIME DEFAULT NULL COMMENT '生效结束时间（到期依据）', `order_no` VARCHAR(64) DEFAULT NULL COMMENT '订阅订单号', `pay_serial` VARCHAR(64) DEFAULT NULL COMMENT '支付渠道流水号', `channel` VARCHAR(32) DEFAULT NULL COMMENT '支付渠道标识', `is_deleted` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除：0 否 / 1 是', `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间', `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间', PRIMARY KEY (`id`), KEY `member_subscription_idx_member_sub_user` (`user_id`), KEY `member_subscription_idx_member_sub_status` (`status`), KEY `member_subscription_idx_member_sub_end` (`end_time`) ) COMMENT = '会员订阅记录表';

-- ============ V24__risk_behavior.sql ============
CREATE TABLE IF NOT EXISTS `risk_behavior_event` ( `id` BIGINT NOT NULL COMMENT '主键（雪花 ID）', `user_id` BIGINT NOT NULL COMMENT '行为用户 ID → user.id', `device_id` VARCHAR(64) DEFAULT NULL COMMENT '设备指纹 / 设备 ID', `event_type` VARCHAR(32) NOT NULL COMMENT '事件类型：LOGIN / SIGN_IN / REDEEM / REWARD / PUBLISH', `biz_id` BIGINT DEFAULT NULL COMMENT '关联业务主键', `ip` VARCHAR(64) DEFAULT NULL COMMENT '来源 IP', `risk_score` INT NOT NULL DEFAULT 0 COMMENT '风险分（预留）', `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '采集时间', PRIMARY KEY (`id`), KEY `risk_behavior_event_idx_behavior_event_user` (`user_id`), KEY `risk_behavior_event_idx_behavior_event_device` (`device_id`), KEY `risk_behavior_event_idx_behavior_event_type` (`event_type`), KEY `risk_behavior_event_idx_behavior_event_create` (`create_time`) ) COMMENT = '用户行为事件表（风控采集源）';
CREATE TABLE IF NOT EXISTS `risk_rule` ( `id` BIGINT NOT NULL COMMENT '主键（雪花 ID）', `rule_code` VARCHAR(32) NOT NULL COMMENT '规则编码（全局唯一）', `rule_name` VARCHAR(64) NOT NULL COMMENT '规则名称', `rule_type` VARCHAR(32) NOT NULL COMMENT 'FREQ / DEVICE_MULTI_ACCOUNT / POINTS_ANOMALY / ACCOUNT_THEFT', `enabled` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否启用：0 关 / 1 开', `action` VARCHAR(16) NOT NULL COMMENT 'LIMIT / MARK / REVIEW / BLOCK', `config_json` VARCHAR(512) DEFAULT NULL COMMENT '规则参数 JSON（windowMinutes / threshold）', `is_deleted` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除：0 否 / 1 是', `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间', `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间', PRIMARY KEY (`id`), UNIQUE KEY `risk_rule_uk_risk_rule_code` (`rule_code`) ) COMMENT = '风控规则配置表';
CREATE TABLE IF NOT EXISTS `risk_decision` ( `id` BIGINT NOT NULL COMMENT '主键（雪花 ID）', `user_id` BIGINT DEFAULT NULL COMMENT '命中用户 ID', `device_id` VARCHAR(64) DEFAULT NULL COMMENT '命中设备 ID', `rule_code` VARCHAR(32) DEFAULT NULL COMMENT '命中规则编码', `event_type` VARCHAR(32) DEFAULT NULL COMMENT '触发事件类型', `decision` VARCHAR(16) NOT NULL COMMENT 'PASS / REVIEW / BLOCK', `risk_level` TINYINT NOT NULL DEFAULT 0 COMMENT '风险等级：0 无 / 1 低 / 2 中 / 3 高', `message` VARCHAR(255) DEFAULT NULL COMMENT '说明', `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '决策时间', PRIMARY KEY (`id`), KEY `risk_decision_idx_decision_user` (`user_id`), KEY `risk_decision_idx_decision_create` (`create_time`), KEY `risk_decision_idx_decision_rule` (`rule_code`) ) COMMENT = '风控决策 / 处置记录表';
