/* tslint:disable */
/* eslint-disable */
/**
 * moyue-system
 * 墨阅小说网 · 平台运营域服务（sample spec，用于验证 openapi-generator 代码生成链路，字段取自 RewardController 真实端点）
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CreateRewardRequest
 */
export interface CreateRewardRequest {
    /**
     * 
     * @type {number}
     * @memberof CreateRewardRequest
     */
    'bookId': number;
    /**
     * 
     * @type {number}
     * @memberof CreateRewardRequest
     */
    'chapterId'?: number;
    /**
     * 
     * @type {number}
     * @memberof CreateRewardRequest
     */
    'amount': number;
    /**
     * 
     * @type {number}
     * @memberof CreateRewardRequest
     */
    'payChannel'?: number;
}

