/* tslint:disable */
/* eslint-disable */
/**
 * moyue-system
 * 墨阅小说网 · 平台运营域服务（sample spec，用于验证 openapi-generator 代码生成链路，字段取自 RewardController 真实端点）
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface RewardOrder
 */
export interface RewardOrder {
    /**
     * 
     * @type {number}
     * @memberof RewardOrder
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof RewardOrder
     */
    'orderNo'?: string;
    /**
     * 
     * @type {number}
     * @memberof RewardOrder
     */
    'userId'?: number;
    /**
     * 
     * @type {number}
     * @memberof RewardOrder
     */
    'bookId'?: number;
    /**
     * 
     * @type {number}
     * @memberof RewardOrder
     */
    'chapterId'?: number;
    /**
     * 
     * @type {number}
     * @memberof RewardOrder
     */
    'amount'?: number;
    /**
     * 1 微信 / 2 支付宝
     * @type {number}
     * @memberof RewardOrder
     */
    'payChannel'?: number;
    /**
     * 0 待支付 / 1 已支付 / 2 已关闭
     * @type {number}
     * @memberof RewardOrder
     */
    'status'?: number;
    /**
     * 
     * @type {string}
     * @memberof RewardOrder
     */
    'payTime'?: string;
    /**
     * 
     * @type {string}
     * @memberof RewardOrder
     */
    'createTime'?: string;
}

